### PR TITLE
Terms

### PR DESCRIPTION
**Pull request by GerardKetuma**
Terms reimplementation to match the specifications and requirements in JIRA.

### CODE REVIEW

**Comment by ys2n** [comment]
Okay.  I fixed a merge error and I am merging.   There were several style changes that need to reviewed.   There especially is a tibetan font issue which I think need to be reviewed by @ThanGrove, since it requires some understanding of Tibetan

**Comment by ThanGrove** [comment]
Where do I go to review the Tibetan font issue?

**Comment by ys2n** [comment]
Actually hold off for now.  I'm rectifying some css merge issues, which is likely the cause.

**Comment by ys2n** [comment]
Ok.  @ThanGrove:  Could you take a look now

**Pull request merged**
